### PR TITLE
Added hdmovie22 and minor fix

### PR DESCRIPTION
**Pull request by rockhero1234**

### CODE REVIEW

**Comment by phisher98** [comment]
Is there any difference on domains ? I think they have same content

**Comment by rockhero1234** [comment]
Both are different sites by same owner and content is not completely same. I added it because hdmovie2 added cloudflare maybe resolved he remove in next domain update.

**Comment by phisher98** [comment]
Okay

**Comment by phisher98** [comment]
If possible change name to Hdmovie22 instead of hd22 looks odd

**Pull request merged**
